stages:
  ingestion:
    cmd: python networksecurity/components/data_ingestion.py
    deps:
    - networksecurity/components/data_ingestion.py
    - networksecurity/entity/config_entity.py
    - networksecurity/entity/artifact_entity.py
    - networksecurity/exception/exception.py
    - networksecurity/logging/logger.py
    - Artifacts/02_23_2025_10_39_01/data_ingestion/feature_store/phisingData.csv

    outs:
    - Artifacts\02_23_2025_10_39_01\data_ingestion\ingested\train.csv:
        persist: true
    - Artifacts\02_23_2025_10_39_01\data_ingestion\ingested\test.csv:
        persist: true
    

  validation:
    cmd: python networksecurity/components/data_validation.py
    deps:
    - networksecurity/components/data_validation.py
    - networksecurity/entity/config_entity.py
    - networksecurity/entity/artifact_entity.py
    - networksecurity/exception/exception.py
    - networksecurity/logging/logger.py
    - networksecurity/utils/main_utils/utils.py
    - networksecurity/constant/training_pipeline
    - Artifacts/02_23_2025_10_39_01/data_ingestion/feature_store/phisingData.csv

    outs:
    - Artifacts/02_23_2025_10_39_01/data_validation/drift_report/report.yaml:
        persist: true
    - Artifacts/02_23_2025_10_39_01/data_validation/validated/test.csv:
        persist: true
    - Artifacts/02_23_2025_10_39_01/data_validation/validated/train.csv:
        persist: true

  transformation:
    cmd: python networksecurity/components/data_transformation.py
    deps:
    - networksecurity/components/data_transformation.py
    - networksecurity/entity/config_entity.py
    - networksecurity/entity/artifact_entity.py
    - networksecurity/exception/exception.py
    - networksecurity/logging/logger.py
    - networksecurity/utils/main_utils/utils.py
    - networksecurity/constant/training_pipeline
    - Artifacts/02_23_2025_10_39_01/data_ingestion/feature_store/phisingData.csv

    outs:
    - Artifacts/02_23_2025_10_39_01/data_transformation/transformed/test.npy:
        persist: true
    - Artifacts/02_23_2025_10_39_01/data_transformation/transformed/train.npy:
        persist: true
    - Artifacts/02_23_2025_10_39_01/data_transformation/transformed_object/preprocessing.pkl:
        persist: true

  training:
    cmd: python networksecurity/components/model_trainer.py

    deps:
    - networksecurity/components/model_trainer.py
    - networksecurity/entity/config_entity.py
    - networksecurity/entity/artifact_entity.py
    - networksecurity/exception/exception.py
    - networksecurity/logging/logger.py
    - networksecurity/utils/main_utils/utils.py
    - networksecurity/utils/ml_utils/model/estimator.py
    - networksecurity/utils/ml_utils//metric/classification_metric.py
    - Artifacts/02_23_2025_10_39_01/data_ingestion/feature_store/phisingData.csv
    outs:
    - Artifacts/02_23_2025_10_39_01/model_trainer/trained_model/model.pkl:
        persist: true